import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

export const metadata: Metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  <html lang="pt-br" className="m-0 p-0 h-full w-full">
   <body>
    <Navbar />
    <main>{children}</main>
    <Footer />
   </body>
  </html>
 );
}
